DudeWeb/DudeWeb/models.py
from datetime import datetime
from flask_login import UserMixin
from DudeWeb import db
from dataclasses import dataclass

class User(UserMixin, db.Model):
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(100), unique=True)
    password = db.Column(db.String(100))
    name = db.Column(db.String(1000))

@dataclass
class Devices(db.Model):
    deviceid: int
    userid: int
    name: str
    tokens: str
    fastadd: str
    timestamp: int

    deviceid = db.Column(db.Integer, primary_key=True)
    userid = db.Column(db.Integer)
    name = db.Column(db.String(1000))
    tokens = db.Column(db.String(10000))
    fastadd = db.Column(db.String(30))
    timestamp = db.Column(db.Integer)

@dataclass
class DevicesLogs(db.Model):
    logid: int
    deviceid: int
    userid: int
    timestamp: int
    logdata: str
    logid = db.Column(db.Integer, primary_key=True)
    deviceid = db.Column(db.Integer)
    userid = db.Column(db.Integer)
    timestamp = db.Column(db.Integer)
    logdata = db.Column(db.String(10000))

class Clients(db.Model):
    ClientID = db.Column(db.Integer, primary_key=True)
    id = db.Column(db.Integer)
    token = db.Column(db.String(10000))
    devicename = db.Column(db.String(1000))
    timestamp = db.Column(db.Integer)
    

DudeWeb/DudeWeb/__init__.py
"""
The flask application package.
"""

from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from datetime import datetime

db = SQLAlchemy()

def timectime(s):
    return datetime.utcfromtimestamp(int(s)).strftime('%Y-%m-%d %H:%M:%S')

def createApp():
    app = Flask(__name__)
    app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///db.sqlite'
    app.config['SECRET_KEY'] = '116E2F91B41949F4B66E3D45A52D6BAC'
    app.jinja_env.filters['ctime'] = timectime

    db.init_app(app)

    login_manager = LoginManager()
    login_manager.login_view = 'auth.login'
    login_manager.init_app(app)

    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint)

    from .views import main as main_blueprint
    app.register_blueprint(main_blueprint)

    from .api import api as api_blueprint
    app.register_blueprint(api_blueprint)

    from .devices import devices as devices_blueprint
    from .devices import getOnlineStatus
    app.register_blueprint(devices_blueprint)
    app.jinja_env.filters['deviceStatus'] = getOnlineStatus

    from .models import User
    @login_manager.user_loader
    def load_user(user_id):
        return User.query.get(int(user_id))

    return app

import DudeWeb.views

DudeWeb/DudeWeb/auth.py
from datetime import datetime
from flask import render_template, Blueprint, redirect, url_for, request, flash
from flask_login import login_user, logout_user, login_required
from werkzeug.security import generate_password_hash, check_password_hash
from DudeWeb import db
from .models import User

auth = Blueprint('auth', __name__)

@auth.route('/login')
def login():
    return render_template('login.html')

@auth.route('/login', methods=['POST'])
def loginPost():
    email = request.form.get('email')
    password = request.form.get('password')
    remember = True if request.form.get('remember') else False

    user = User.query.filter_by(email=email).first()

    if not user or not check_password_hash(user.password, password):
        flash('Please check your login details and try again.')
        return redirect(url_for('auth.login'))

    login_user(user, remember=remember)
    return redirect(url_for('main.profile'))

@auth.route('/signup')
def signup():
    return render_template('signup.html')

@auth.route('/signup', methods=['POST'])
def signupPost():
    email = request.form.get('email')
    name = request.form.get('name')
    password = request.form.get('password')

    user = User.query.filter_by(email=email).first()

    if user:
        flash('Email address already exists')
        return redirect(url_for('auth.signup'))

    new_user = User(email=email, name=name, password=generate_password_hash(password, method='sha256'))

    db.session.add(new_user)
    db.session.commit()

    return redirect(url_for('auth.login'))

@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('main.index'))

DudeWeb/DudeWeb/views.py
"""
Routes and views for the flask application.
"""

from datetime import datetime
from flask import render_template, Blueprint
from flask_login import login_required, current_user
from DudeWeb import db

main = Blueprint('main', __name__)

@main.route('/')
def index():
    currentPageTitle = "Index"
    return render_template('index.html', currentPageTitle=currentPageTitle)

@main.route('/profile')
@login_required
def profile():
    currentPageTitle = "Profile"
    return render_template('profile.html', currentPageTitle=currentPageTitle, name=current_user.name)

DudeWeb/DudeWeb/templates/adddevice.html
{% extends "base.html" %} {% block content %}
{% with messages = get_flashed_messages() %}
{% if messages %}
<div>
    {{ messages[0] }}
</div>
{% endif %}
{% endwith %}
<form method="POST" action="{{ url_for('devices.add') }}">
    <div>
        <input type="text" name="name" placeholder="Name" autofocus="">
    </div>

    <button>Add</button>
</form>
{% endblock %}

DudeWeb/DudeWeb/templates/base.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>{{ currentPageTitle }}</title>
</head>

<body>
    <div name="navbar">
        <a href="{{ url_for('main.index') }}" class="navbar-item">
            Home
        </a>
        {% if current_user.is_authenticated %}
        <a href="{{ url_for('main.profile') }}" class="navbar-item">
            Profile
        </a>
        <a href="{{ url_for('devices.index') }}" class="navbar-item">
            Devices
        </a>
        {% endif %}
        {% if not current_user.is_authenticated %}
        <a href="{{ url_for('auth.login') }}" class="navbar-item">
            Login
        </a>
        <a href="{{ url_for('auth.signup') }}" class="navbar-item">
            Sign Up
        </a>
        {% endif %}
        {% if current_user.is_authenticated %}
        <a href="{{ url_for('auth.logout') }}" class="navbar-item">
            Logout
        </a>
        {% endif %}
    </div>
    <div name="body">
        {% block content %} {% endblock %}
    </div>
</body>
</html>

DudeWeb/DudeWeb/templates/deletedevice.html
{% extends "base.html" %} {% block content %}
<form method="POST" action="{{ url_for('devices.deletePost') }}">
    <div>
        <input type="hidden" name="deviceid" value="{{ deviceid }}">
    </div>

    <button>Confirm deletion of device {{ deviceid }}</button>
</form>
<form action="{{ url_for('devices.index') }}">
    <input type="submit" value="Cancel" />
</form>
{% endblock %}

DudeWeb/DudeWeb/templates/devices.html
{% extends "base.html" %} {% block content %}
{% with messages = get_flashed_messages() %}
{% if messages %}
<div>
    {{ messages[0] }}
</div>
{% endif %}
{% endwith %}
<h2>
    <a href="{{ url_for('devices.add') }}" class="navbar-item">
        Add device
    </a>
</h2>

{% if devices_array %}
<div>
    <table>
        <td>Device ID</td>
        <td>Name</td>
        <td>Status</td>
        <td>FastAdd</td>
        <td>Token</td>
        <td>Act</td>
        {% for i in devices_array %}
        <tr>
            <td>{{ i.deviceid }}</td>
            <td>{{ i.name }}</td>
            <td>{{ i.timestamp | deviceStatus }}</td>
            <td>{{ i.fastadd }}</td>
            <td>{{ i.tokens }}</td>
            <td><a href="{{ url_for('devices.log', id=i.deviceid) }}">Log</a></td>
            <td><a href="{{ url_for('devices.fastadd', id=i.deviceid) }}">New fastadd</a></td>
            <td><a href="{{ url_for('devices.edit', id=i.deviceid) }}">Edit</a></td>
            <td><a href="{{ url_for('devices.delete', id=i.deviceid) }}">Delete</a></td>
        </tr>
        {% endfor %}
    </table>
</div>
{% endif %}

{% endblock %}

DudeWeb/DudeWeb/templates/deviceslogs.html
{% extends "base.html" %} {% block content %}

Device logs for {{ deviceid }}
<br>
{% if deviceslogs_array %}
<div>
    <table>
        <td>Log ID</td>
        <td>Time</td>
        <td>Data</td>
        {% for i in deviceslogs_array %}
        <tr>
            <td>{{ i.logid }}</td>
            <td>{{ i.timestamp | ctime }}</td>
            <td>{{ i.logdata }}</td>
        </tr>
        {% endfor %}
    </table>
</div>
{% else %}
    Empty logs
{% endif %}

{% endblock %}

DudeWeb/DudeWeb/templates/editdevice.html
{% extends "base.html" %} {% block content %}
<form method="POST" action="{{ url_for('devices.editPost') }}">
    <div>
        <input type="hidden" name="deviceid" value="{{ deviceid }}">
    </div>

    <div>
        <input type="text" name="name" placeholder="Name" value="{{ devicename }}">
    </div>

    <button>Confirm edition of device {{ deviceid }}</button>
</form>
<form action="{{ url_for('devices.index') }}">
    <input type="submit" value="Cancel" />
</form>
{% endblock %}

DudeWeb/DudeWeb/templates/fastadd.html
{% extends "base.html" %} {% block content %}
<form method="POST" action="{{ url_for('devices.fastaddPost') }}">
    <div>
        <input type="hidden" name="deviceid" value="{{ deviceid }}">
    </div>

    <button>Confirm new fastadd generation for device {{ deviceid }}</button>
</form>
<form action="{{ url_for('devices.index') }}">
    <input type="submit" value="Cancel" />
</form>
{% endblock %}

DudeWeb/DudeWeb/templates/index.html
{% extends "base.html" %} {% block content %}
<h1 class="title">
    Index page
</h1>
<h2 class="subtitle">
    just landing page
</h2>
{% endblock %}

DudeWeb/DudeWeb/templates/login.html
{% extends "base.html" %} {% block content %}
{% with messages = get_flashed_messages() %}
{% if messages %}
<div>
    {{ messages[0] }}
</div>
{% endif %}
{% endwith %}
<form method="POST" action="{{ url_for('auth.login') }}">
    <div>
        <input type="email" name="email" placeholder="Your Email" autofocus="" />
    </div>

    <div>
        <input type="password" name="password" placeholder="Your Password" />
    </div>

    <div>
        <label>
            <input type="checkbox" />
            Remember me
        </label>
    </div>

    <button>Login</button>
</form>
{% endblock %}

DudeWeb/DudeWeb/templates/profile.html
{% extends "base.html" %} {% block content %}
<h1>
    Welcome, {{ name }}!
</h1>
{% endblock %}

DudeWeb/DudeWeb/templates/signup.html
{% extends "base.html" %} {% block content %}
{% with messages = get_flashed_messages() %}
{% if messages %}
<div>
    {{ messages[0] }}. Go to <a href="{{ url_for('auth.login') }}">login page</a>.
</div>
{% endif %}
{% endwith %}
<form method="POST" action="{{ url_for('auth.signup') }}">
    <div>
        <input type="email" name="email" placeholder="Email" autofocus="">
    </div>

    <div>
        <input type="text" name="name" placeholder="Name" autofocus="">
    </div>

    <div>
        <input type="password" name="password" placeholder="Password">
    </div>

    <button>Sign Up</button>
</form>
{% endblock %}